### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by greg-sys** [aschubauer/SiderealAstroPy#1]
Hello, when I try to run transits.py I get the following:

  File "transits.py", line 86
    ASPECTS.append((*nextAspect, planet1, planet2))
                    ^
SyntaxError: invalid syntax

I'm new to Python and it may be that I didn't set up the project properly. Could you please advise?

**Comment by aschubauer** [comment]
Hi! There isn't a syntax error in that part of the code, so something else is causing that error. Have you changed the code at all? If you're using an IDE, can you run transits.py using the terminal/console and see if you're still getting the error?

If that doesn't work, can you post the code of the function that's raising the syntax error? The incorrect code is probably above line 86.

**Comment by greg-sys** [comment]
Hi, thanks for getting back to me! I downloaded PyCharm and ran the code in it. It looks like the problem was that I didn't have pyswisseph set up so that the code could find it. So, I installed pyswisseph manually using PyCharm and that problem went away. Now I'm getting a new error, though:

"
/usr/local/bin/python3.7 /Users/greg/SiderealAstroPy/transits.py
Enter 'Z' to switch to tropical zodiac: T

Current time: Wed Dec 02 2020 16:28:42

Traceback (most recent call last):
  File "/Users/greg/SiderealAstroPy/transits.py", line 313, in <module>
    main()
  File "/Users/greg/SiderealAstroPy/transits.py", line 229, in main
    printPlanetPositions(now, 3, sidereal=sidereal)
  File "/Users/greg/SiderealAstroPy/transits.py", line 190, in printPlanetPositions
    planetSigns = list(swe.split_deg(planetpos[i][0],8) for i in range(len(planetpos)))
  File "/Users/greg/SiderealAstroPy/transits.py", line 190, in <genexpr>
    planetSigns = list(swe.split_deg(planetpos[i][0],8) for i in range(len(planetpos)))
TypeError: must be real number, not tuple

Process finished with exit code 1"

The code here is:

def printPlanetPositions(dt, orb, sidereal=True):
	dt_tup = dt.timetuple()[:6]
	jt = swe.utc_to_jd(*dt_tup,swe.GREG_CAL)
	planetpos = list(swe.calc_ut(jt[1], i, flag=int(sidereal)*swe.FLG_SIDEREAL+swe.FLG_SPEED) for i in range(len(PLANETKEY)))
	planetSigns = list(swe.split_deg(planetpos[i][0],8) for i in range(len(planetpos)))

It looks like the calc_ut function returns a tuple, which isn't accepted by split_deg as input...? But I may not be following the code right, or again it may be that there is some project setting I need to adjust. Any advice would be appreciated, thanks again.

**Comment by aschubauer** [comment]
Thanks for flagging this! It looks like the newer version of pyswisseph has changed some function inputs/outputs. I haven't gone through and updated the code for this project, but if you install the previous version of pyswisseph (2.00.00), it should work.

I've updated this repository and the README with more info – in short, if you install pipenv, download this project again, and run `pipenv install`, you'll have the right version of pyswisseph for this project, and you can use the newer version for other projects. I hope this helps!

**Comment by greg-sys** [comment]
Thanks! I followed your instructions and now the project is working. The transits.py script shows the upcoming conjunction of Jupiter and Saturn on the 21st. I appreciate your assistance on this!

**Comment by aschubauer** [comment]
Awesome, I'm glad to hear it worked!
